services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./app/gallery:/var/www/html/gallery
      - ./app/cache:/var/www/html/cache
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=gallery_db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gallery_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql